[package]
name = "hello-word-cargo"
version = "0.1.0"
authors = ["Amzal abdel <am.amzal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
